### ISSUE TITLE
无法保存登陆信息

### ISSUE THREAD

**Issue by WinkeyLin** [AiRanthem/xmu-daily-report#1]
每次使用的时候总是提示登陆过期，需要重新输入账号密码略显麻烦😂
另外的一个小建议，写一个 bat 脚本用作启动器就好了，放一个只有引导功能的 py 文件有点奇怪

很棒的工具，让大佬费心了~

**Comment by AiRanthem** [comment]
同学你好😂首先谢谢你使用这个玩具（真的没想到会有人来点开这个仓库🤦‍♂️

首先是登陆过期的问题，似乎是系统在某天之后对用户鉴权做了改进，无脑保存cookie的方法没有办法保存用户token。由于本来就是为了熟悉selenium而写的练手项目，我也没有进一步地去维护。

bat脚本的话，其实我是真的不会写😂我一直习惯用Linux编程，把这个玩具迁移到Windows也是心血来潮。谢谢你的建议，我会去学习一下ps1脚本和bat脚本，确实比用py文件来做启动器和提示脚本效率很多。
