### ISSUE TITLE
error code #1

### ISSUE THREAD

**Issue by juuinn** [AiRanthem/xmu-daily-report#10]
同学，你好。我试着在GitHub上运行这个自动打卡的，发现每次都提示相同错误。我点开看了一下，发现错误如下
<img width="953" alt="Screen Shot 2022-02-05 at 11 44 33 AM" src="https://user-images.githubusercontent.com/10397482/152627663-15f8daff-b32b-4d4a-adf8-824041d0e5b7.png">
：

**Comment by AiRanthem** [comment]
请确保配置文件正确编辑并正确设置CONFIG，具体参考：https://github.com/AiRanthem/xmu-daily-report#2-%E7%BC%96%E8%BE%91%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by AiRanthem** [comment]
你好，请问问题解决了吗？时间过长我要关闭这个issue了。

**Comment by juuinn** [comment]
重新配置了CONFIG，也是不行。应该不是密码错误。

**Comment by AiRanthem** [comment]
麻烦把CONFIG的内容发出来，敏感数据用*代替

**Comment by juuinn** [comment]
{
  "config": [
    {
      "username": "216201888888",
      "password": "**********",
      "password_vpn": "*********",
      "email": "*****888@qq.com"
    },
    {
      "username": "2*****888888",
      "password": "kiwzyn*******0fisky",
      "password_vpn": "*******",
      "email": "*****888@qq.com"
    }
  ]
}

**Comment by AiRanthem** [comment]
您是一个人使用吗？username与email请输入正确的学号与邮箱而不要写没意义的数字，密码也请正确输入不要留空。如果是一个人使用的话，请参考：{
"config": [
{
"username": "21620113232",
"password": "password",
"password_vpn": "vpnpassword",
"email": "123456789@qq.com"
}
]
}

**Comment by AiRanthem** [comment]
麻烦仔细阅读配置文件那一章，你的配置是完全错误的。

**Comment by juuinn** [comment]
好的，谢谢

**Comment by juuinn** [comment]
我通过这个打卡成功了，但是在打卡的网站上并没有这次打卡记录，请问是什么情况

**Comment by AiRanthem** [comment]
1. 如果识别到今天还没有打卡，则完成打卡并发送邮件“打卡成功”
2. 如果识别到今天已经打过卡，则不进行打卡并直接发送邮件“今日已打卡”，第二天会自动进行打卡
3. 如果发生错误（一般是学校服务器挂了），则发送邮件“打卡失败”，遇到这个问题请暂时手动打卡一天，第二天会恢复正常
4. 如果因为一些重大原因（网页结构变动、逻辑变化等），需要参考文档进行代码更新
