### ISSUE TITLE
提示框确定问题

### ISSUE THREAD

**Issue by lukan217** [AiRanthem/xmu-daily-report#2]
昨天又忘记打卡，气的我就想自己写一个自动打卡脚本，搜了一下没有到大佬你已经做了个这样的项目，太感谢了！研究下了源码，发现存在一个问题，就是现在我们点击保存后会弹出一个提示框，点确认才算提交成功

**Comment by AiRanthem** [comment]
是这样的，一来我当时是怕不能确定是否能成功运行，二来是我怕调试的时候重复提交过多次出什么问题，所以留了最后一步没有做。如果你有兴趣做完的话可以PR啊哈哈哈
