### ISSUE TITLE
希望在 README 文件中添加修改地区项内容

### ISSUE THREAD

**Issue by Cyber-Yin** [AiRanthem/xmu-daily-report#20]
我是思明区的学生，但是程序中的默认地区是翔安区，所以打卡时地理位置会出错。
建议提醒一下思明同学在 fork 后修改 `XMUAutoCheckIn.py` 文件的 `148` 行为思明区。
感谢作者！

**Comment by WinkeyLin** [comment]
感谢，没注意看差点出事

**Comment by AiRanthem** [comment]
目前有个朋友正在帮忙开发用户友好的图形化配置界面，到时候这些都会变成可配置项。目前地区相关代码可自行删除

**Comment by AiRanthem** [comment]
目前有个朋友正在帮忙开发用户友好的图形化配置界面，到时候这些都会变成可配置项。目前地区相关代码可根据楼主的方法自行修改

**Comment by AiRanthem** [comment]
目前有个朋友正在帮忙开发用户友好的图形化配置界面，到时候这些都会变成可配置项。地区相关问题可根据楼主的方法自行修改代码临时解决。

**Comment by AiRanthem** [comment]
新版本已上线https://github.com/AiRanthem/xmu-daily-report#%E7%BD%AE%E9%A1%B6%E5%85%AC%E5%91%8A
