### ISSUE TITLE
打卡系统需要重新填写校区和宿舍

### ISSUE THREAD

**Issue by weaey** [AiRanthem/xmu-daily-report#21]
今天打卡失败，发现是打卡系统中的校区，是否住校，宿舍编号等需要重新填写，对于多个账户，不知道如何添加不同的宿舍号

**Comment by lovemaoli** [comment]
（可以写在secret里

**Comment by AiRanthem** [comment]
改动比较大，如果配置太复杂容易影响非专业同学使用。现在在开发图形化配置界面，可以方便地配置更多选项，等配置界面到位之后会更新打卡脚本。工作量比较大，我一个人做起来需要时间。

**Comment by weaey** [comment]
> 改动比较大，如果配置太复杂容易影响非专业同学使用。现在在开发图形化配置界面，可以方便地配置更多选项，等配置界面到位之后会更新打卡脚本。工作量比较大，我一个人做起来需要时间。

开发可视化界面会不会比较危险，毕竟现在还停留在学习交流的层面

**Comment by AiRanthem** [comment]
新版本已上线https://github.com/AiRanthem/xmu-daily-report#%E7%BD%AE%E9%A1%B6%E5%85%AC%E5%91%8A
