### ISSUE TITLE
如何实现多账号的不同楼栋选择

### ISSUE THREAD

**Issue by weaey** [AiRanthem/xmu-daily-report#22]
我想要实现多账号的不同楼栋选择和宿舍号的填写，在CONFIG里增加了building和room，然后增加了下拉楼栋和填写房间号的代码，
![595f0ab2a69dd85ad52d0507ed42e08](https://user-images.githubusercontent.com/66466237/161191597-6f2f7cd1-9dd7-4ef3-bad2-461c1df63b6c.png)
![54f33381d17e813941a2a8bb12619d6](https://user-images.githubusercontent.com/66466237/161191609-9cc6ae52-fa7c-4e27-9a31-8cee793e3bf1.png)
在这里如何将build和room替换为像username一样的变量，我修改了一下以下两处代码，不知道具体该怎么搞，
![23d8998eba20509fdb539470d95c3d7](https://user-images.githubusercontent.com/66466237/161191739-3502084d-466f-4e65-825f-ab16f3bed594.png)
![f2d8a9bbf15a702405f79c4cac16563](https://user-images.githubusercontent.com/66466237/161191751-5998682d-0502-4480-aef9-a107b797c7d5.png)

**Comment by AiRanthem** [comment]
具体的看.github目录，或者等重构版本更新

**Comment by weaey** [comment]
> 

改这些吗https://github.com/AiRanthem/xmu-daily-report/issues/22#issuecomment-1085388650

**Comment by weaey** [comment]
> 具体的看.github目录，或者等重构版本更新

改这些吗
![捕获](https://user-images.githubusercontent.com/66466237/161193100-57e4b94c-80f7-41f0-903a-70e4274c69ec.PNG)
