### ISSUE TITLE
临时替代方案

### ISSUE THREAD

**Issue by CyberCatQ** [AiRanthem/xmu-daily-report#23]
鉴于打卡系统变更
此Fork提供了一个临时替代方案：https://github.com/CyberCatQ/xmu-daily-report
需要修改secret中的内容更新为template的新项目

此外 对student number进行了mask 以免在log文件中泄露个人信息。
希望有所帮助
仅为临时替代方法 故不提交PR 期待作者进一步更新

**Comment by weaey** [comment]
很好用

**Comment by AiRanthem** [comment]
新版本已上线

**Comment by AiRanthem** [comment]
另外如果你觉得你的mask效果好的话可以给我提PR
