### ISSUE TITLE
多账号打卡失败不发送邮件

### ISSUE THREAD

**Issue by weaey** [AiRanthem/xmu-daily-report#24]
有一个问题就是，对于多账号配置，当第一个账号打卡10次失败后，不会继续运行，导致只有第一个人收到打卡失败的邮件，后面的账号没有邮件提醒

**Comment by AiRanthem** [comment]
1. 确保更新到最新版本
2. 如果还有问题尽量自己解决之后推PR
3. 自己无法解决附上完整运行日志提Issue

**Comment by AiRanthem** [comment]
这个问题已经推补丁解决
