### ISSUE TITLE
代码运行成功 网页上没保存成功

### ISSUE THREAD

**Issue by binbinjiang** [AiRanthem/xmu-daily-report#3]
兄弟 运行成功了 但是登录网页没有发现保存成功。这是怎么肥事。另外 我修改了点代码，可以全天监控的。方便的交流的话，邮件发您私人账号

**Comment by AiRanthem** [comment]
首先谢谢关注这个项目。
最近打卡网页更新了结构，“保存”按钮外面多了一层div，定位会失败。playwright我在部署到服务器时遇到了一些问题，加上最近实验室比较忙，没有精力去维护它。一劳永逸地定位“保存”按钮可以使用这个xpath："//span[starts-with(text(),'保存')][1]"。您修改的代码欢迎提PR，我会通过。
如果您有兴趣，可以研究研究playwright在服务器上的部署。现在似乎需要安装X并设置display环境变量才能调起无头的chromium。这样有一点缺乏优雅。或许通过docker部署会好一点？

**Comment by binbinjiang** [comment]
感谢你的回复 我等会先测试一下， 我在你的基础上直接加了几行判断，部署在我的服务器上可以运行。你的代码简洁，挺好的，等我先按你的提示修改一下保存 再确定代码提交

**Comment by binbinjiang** [comment]
兄弟 还有点小问题 方便的话 加个微信 我邮箱914711123@qq.com，私发我wechat Id, 平时也可以技术探讨
