### ISSUE TITLE
多账号登录失败

### ISSUE THREAD

**Issue by weaey** [AiRanthem/xmu-daily-report#30]
貌似账号登陆后，会记住账号密码，登录第二个账号时，会自动跳转上一个账号的健康打卡，导致第二个账号登录失败后，进行vpn登录，vpn登录成功后第二个账号打卡成功，但是第三个账号无论是直接连接还是vpn登录都会失败。，导致第三个账号打卡失败

**Comment by AiRanthem** [comment]
应该是driver的单例导致的，你有兴趣可以改一改让打卡前生成driver对象，一个账号弄完再close掉。具体看webdriver.py。最近我在忙一个演出，没什么空

**Comment by AiRanthem** [comment]
新版本已经修复这个bug
