### ISSUE TITLE
打卡失败但是没有邮件提醒

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [AiRanthem/xmu-daily-report#34]
在4月末的时候发现了这个问题，具体是确认了成功配置后，在xmuxg网站上是没有打卡的状态，但是在github上的workflow是
![image](https://user-images.githubusercontent.com/69394845/166660762-e926391b-796a-403d-8523-3420bf44d95c.png)
这样成功执行的。
在邮箱里没有受到任何关于打卡的汇报，成功和失败都没有。

**Comment by AiRanthem** [comment]
更新

**Comment by Uc207Pr4f57t9-251** [comment]
我重新部署了一下，看看能不能成
