### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Klein-in** [AiRanthem/xmu-daily-report#35]
您好，请问配置完了之后没收到邮件是咋回事啊

**Comment by Klein-in** [comment]
收到了没事了。还想问问这个邮件发送时间是随机的吗？还有就是我不开电脑不开GitHub它也能自动打卡吗？

**Comment by AiRanthem** [comment]
每天9点半到11点会随机选一个时间自动打卡，不用管，哪天出问题了看公告或更新。

**Comment by Klein-in** [comment]
好酷哦，谢谢你！
