### ISSUE TITLE
放到自己的服务器上运行出现错误

### ISSUE THREAD

**Issue by Bc-Gg** [AiRanthem/xmu-daily-report#38]
本地服务器现实打卡成功，但是上了官网之后显示并没有打卡成功。
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/74237587/170392376-509db110-142e-47e9-9d84-ffff0fdd1571.png">

**Comment by AiRanthem** [comment]
查看文档测试一章。
自己服务器上运行情况不可控，我不打算提供支持，同时以后报告任何错误请附带完整日志，我没有虚空debug的超能力。
