### ISSUE TITLE
新bug

### ISSUE THREAD

**Issue by Data-Adventure** [AiRanthem/xmu-daily-report#48]
![image](https://user-images.githubusercontent.com/83524608/184522427-f0bc9421-b8f8-444b-9df6-f26f7764c206.png)
在健康史处，新加入了最近一次核酸检测时间。导致自动打卡无法正常运行。

**Comment by AiRanthem** [comment]
更新了

**Comment by wmkai** [comment]
> 更新了

更新在哪了呀

**Comment by amluckydave** [comment]
> 更新了

同样没找到

**Comment by AiRanthem** [comment]
使用开源项目前，记得养成读文档的习惯，不然容易被别人安利《提问的艺术》
https://github.com/AiRanthem/xmu-daily-report/blob/master/README.md#%E4%BB%93%E5%BA%93%E7%BB%B4%E6%8A%A4

**Comment by AiRanthem** [comment]
按照文档里面的更新一节删除现有仓库重新fork母仓库更新一下
