### ISSUE TITLE
您好，请问下校外填报如何配置，这部分有相关文档吗

### ISSUE THREAD

**Issue by wmkai** [AiRanthem/xmu-daily-report#51]

**Comment by AiRanthem** [comment]
临时修改的话，手动打卡一次把在校改成不在校就行
长期修改的话，配置文件里inschool一项改成“不在校”

**Comment by wmkai** [comment]
> 临时修改的话，手动打卡一次把在校改成不在校就行 长期修改的话，配置文件里inschool一项改成“不在校”

感谢回复，我昨天修改了之后，会报这样的错误，这是啥意思呢？
<img width="368" alt="image" src="https://user-images.githubusercontent.com/39148461/185594333-13e412c6-5c7e-4bd5-810f-76a1e1995454.png">
