### ISSUE TITLE
浏览器打不开vpn界面导致的打卡失败

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [AiRanthem/xmu-daily-report#55]
这几天打卡出现失败的情况，在10月17更新了这个脚本重新执行也还是打卡失败。
于是去action看日志看到了这个事件以及后面的警告。
似乎是浏览器打开不了webvp界面？
请问是因为近期某大会造成的？还是什么新的bug？

附上错误日志：

[20](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:20)22-10-17 16:51:08,9[21](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:21) - [INFO*** - 已配置 1 个账号
20[22](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:22)-10-17 16:51:08,922 - [INFO*** - 账号【 **** [23](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:23)3】正在运行
2022-10-17 16:51:08,922 - [INFO*** - 第1次尝试
2022-10-17 16:51:09,918 - [INFO*** - 准备工作完成
2022-10-17 16:51:09,918 - [INFO*** - 正在请求登录页面
2022-10-17 16:51:18,315 - [ERROR*** - 确认 VPN选择账号登录 存在 失败
2022-10-17 16:51:18,315 - [ERROR*** - Alert Text: 您的浏览器无法正常打开WEBVPN界面，请更新您的浏览器
Message: unexpected alert open: ***Alert text : 您的浏览器无法正常打开WEBVPN界面，请更新您的浏览器***
  (Session info: headless chrome=106.0.5[24](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:24)9.91)
Stacktrace:
#0 0x55c5128f12c3 <unknown>
#1 0x55c5126fa83a <unknown>
#2 0x55c51276982a <unknown>
#3 0x55c512751d63 <unknown>
#4 0x55c5127267e3 <unknown>
#5 0x55c512727a21 <unknown>
#6 0x55c51293f18e <unknown>
#7 0x55c512942622 <unknown>
#8 0x55c5129[25](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:25)aae <unknown>
#9 0x55c51[29](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:29)4[32](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:32)a3 <unknown>
#10 0x55c512919ecf <unknown>
#11 0x55c51296[35](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:35)88 <unknown>
#12 0x55c51296[37](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:37)06 <unknown>
#13 0x55c51297d8b2 <unknown>
#14 0x7f807[41](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:6:41)86609 <unknown>

以及除了这个错误之外，还看到在action下面出现了两个警告：

[build](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/setup-python, actions/checkout
Show more

[build](https://github.com/Uc207Pr4f57t9-251/xmu-daily-report/actions/runs/3263700223/jobs/5363166534#step:3:6)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Show more

之前一直使用快两年了，一直比较稳定，感谢大佬写的项目。

**Comment by andyourself** [comment]
+1 ！！

**Comment by AiRanthem** [comment]
某大会导致的

**Comment by AiRanthem** [comment]
问题已经修复，更新最新版本即可
